name: ci

on: push

jobs:
  lint:
    name: Run tests
    runs-on: ubuntu-latest
    container: 'node:16-slim'
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run lint
  build: 
    name: Build
    runs-on: ubuntu-latest
    container: 'node:16-slim'
    steps: 
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run build